sudo: required
os: osx
language: node_js
matrix:
  include:
    - osx_image: xcode7.3
      node_js: "6"
      env: DEVICE=9.3 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip

    - osx_image: xcode8.3
      node_js: "6"
      env: DEVICE=9.3 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip
    - osx_image: xcode8.3
      node_js: "6"
      env: DEVICE=10.3 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip

    - osx_image: xcode9
      node_js: "6"
      env: DEVICE=10.3 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip
    - osx_image: xcode9
      node_js: "6"
      env: DEVICE=11.0 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip

script:
  - curl -L http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.gz -o apache-ant-1.9.6-bin.tar.gz
  - tar xfz apache-ant-1.9.6-bin.tar.gz --directory ../
  - export PATH=`pwd`/../apache-ant-1.9.6/bin:$PATH
  - curl -L https://archive.apache.org/dist/maven/maven-3/3.2.3/binaries/apache-maven-3.2.3-bin.tar.gz -o apache-maven-3.2.3-bin.tar.gz
  - tar xvfz apache-maven-3.2.3-bin.tar.gz --directory ../
  - export PATH=`pwd`/../apache-maven-3.2.3/bin:$PATH
  - bash .travis/build.sh
