sudo: required
os: osx
language: node_js
matrix:
  include:
    - osx_image: xcode7.3
      node_js: "6"
      env: DEVICE=9.3 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip

    - osx_image: xcode8.3
      node_js: "6"
      env: DEVICE=9.3 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip
    - osx_image: xcode8.3
      node_js: "6"
      env: DEVICE=10.3 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip

    - osx_image: xcode9
      node_js: "6"
      env: DEVICE=10.3
    - osx_image: xcode9
      node_js: "6"
      env: DEVICE=11.0 CN1_RUNTESTS_IOS_SIMULATOR=1 CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip

script:
  - bash .travis/build.sh
