language: java
jdk: oraclejdk8
os: osx
env:
  - CN1_RUNTESTS_IOS_SIMULATOR=1
  #- CN1_RUNTESTS_JAVASE=1
  #- CN1_RUNTESTS_IOS_DEVICE=1
  - CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip
before_script:
  - brew install ant
script:
  - bash .travis/build.sh
