env:
  global:
    - CN1_SOURCES=https://github.com/codenameone/CodenameOne/archive/master.zip
matrix:
  include:
    - language: android
      jdk: oraclejdk8
      env: CN1_PLATFORM=android CN1_RUNTESTS_ANDROID_EMULATOR=1
      addons:
        apt:
          packages:
            - ant
            - maven
      android:
        components:
          - platform-tools
          - android-18
          - addon-google_apis-google-18
          - sys-img-armeabi-v7a-google_apis-18

    - osx_image: xcode7.3
      env: CN1_PLATFORM=ios DEVICE=9.3 CN1_RUNTESTS_IOS_SIMULATOR=1
      sudo: required
      os: osx
      language: node_js

    - osx_image: xcode8.3
      node_js: "6"
      env: CN1_PLATFORM=ios DEVICE=9.3 CN1_RUNTESTS_IOS_SIMULATOR=1
      sudo: required
      os: osx
      language: node_js

    - osx_image: xcode8.3
      node_js: "6"
      env: CN1_PLATFORM=ios DEVICE=10.3 CN1_RUNTESTS_IOS_SIMULATOR=1
      sudo: required
      os: osx
      language: node_js

    - osx_image: xcode9
      node_js: "6"
      env: CN1_PLATFORM=ios DEVICE=10.3 CN1_RUNTESTS_IOS_SIMULATOR=1
      sudo: required
      os: osx
      language: node_js

    - osx_image: xcode9
      node_js: "6"
      env: CN1_PLATFORM=ios DEVICE=11.0 CN1_RUNTESTS_IOS_SIMULATOR=1
      sudo: required
      os: osx
      language: node_js

script:
  - bash .travis/build.sh;
